services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-php-fpm
    restart: unless-stopped
#    volumes: 
#      - ./:/var/www/app # for dev
    networks:
      - products-network
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=16&charset=utf8
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: products-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - products-network

  postgres:
    image: postgres:17-alpine
    container_name: products-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - products-postgres-data:/var/lib/postgresql/data:rw
    networks:
      - products-network

networks:
  products-network:
    driver: bridge

volumes:
  products-postgres-data:
